version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - SERVER=backend
    ports:
      - 8701:8701
    #depends_on:
      #- backend
    volumes:
      - ./frontend:/workspace
      - ./data:/data
    restart: always

  #backend:
    #build: backend
    #ports:
      #- 23456:23456
    ##volumes:
      ##- ./workspace:/workspace
      ##- ./data:/data
    #restart: always
